PL/Controllers/CargaMasivaUsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System;
using System.Data;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace PL.Controllers
{
    public class CargaMasivaUsuarioController : Controller
    {
        private IHostingEnvironment _environment;
        private IConfiguration _configuration;

        public CargaMasivaUsuarioController(IHostingEnvironment environment, IConfiguration configuration)
        {
            _environment = environment;
            _configuration = configuration;
        }
        public ActionResult Index(ML.Result result)
        {            
            string display = HttpContext.Session.GetString("Display");
            string file = HttpContext.Session.GetString("File");
            string session = HttpContext.Session.GetString("PathArchivo");
            string correct = HttpContext.Session.GetString("Correct");
            if (session == null)
            {
                if (display == null || display == "none"){ ViewBag.Display = "none"; }
                ViewBag.Correct = false;
                return View(result);
            }
            else
            {
                if (file != null || file == "") { ViewBag.File = file; }
                if (correct == "true"){ ViewBag.Correct = true; }                
                return View(result);
            }         
                
        }

        [HttpPost]
        public ActionResult Index(IFormFile archivoTxt)
        {            
            string connSQL = "Data Source=.;Initial Catalog=DRosasProgramacionNCapas;Persist Security Info=True;User ID=sa;Password=pass@word1; TrustServerCertificate=True;";
            SqlConnection sqlConnection = new SqlConnection(connSQL);

            int counter = 0;
            string line = "";
            
            string fileDelimiter = ",";

            using (StreamReader reader = new StreamReader(archivoTxt.OpenReadStream()))
            {
                sqlConnection.Open();
                while ((line = reader.ReadLine()) != null)
                {                    
                    if (counter > 0)
                    {
                        //string query = "INSERT INTO Usuario VALUES('" + line.Replace(fileDelimiter, "','") + "')";
                        string query = "EXEC UsuarioAdd '" + line.Replace(fileDelimiter, "','") + "'";

                        //ejecutar query
                        SqlCommand cmd = new SqlCommand(query, sqlConnection);
                        cmd.ExecuteNonQuery();
                    }
                    counter++;
                }
            }
            sqlConnection.Close();
            ViewBag.Message = "Exito en la carga";
            return View("Modal");

        }//Index(archivo Txt)

        [HttpPost]
        public ActionResult Excel()
        {
            IFormFile archivo = Request.Form.Files["archivoExcel"];

            if (HttpContext.Session.GetString("PathArchivo") == null)
            {
                if (archivo != null)
                {
                    //Si el archivo trae información
                    if (archivo.Length > 0)
                    {
                        //obtener el nombre de nuestro archivo
                        string fileName = Path.GetFileName(archivo.FileName);

                        string folderPath = _configuration["PathFolder:value"];
                        string extensionArchivo = Path.GetExtension(archivo.FileName).ToLower();
                        string extensionXlsx = _configuration["TipoExcel"];
                        string extensionXls = _configuration["TipoXls"];
                        string extensionCsv = _configuration["TipoCsv"];

                        if (extensionArchivo == extensionXlsx || extensionArchivo == extensionXls || extensionArchivo == extensionCsv)
                        {
                            string filePath = Path.Combine(_environment.ContentRootPath, folderPath, Path.GetFileNameWithoutExtension(fileName)) + '-' + DateTime.Now.ToString("yyyyMMddHHmmss") + ".xlsx";

                            if (!System.IO.File.Exists(filePath))
                            {
                                using (FileStream stream = new FileStream(filePath, FileMode.Create))
                                {
                                    archivo.CopyTo(stream);
                                }

                                string connectionString = _configuration["ConnectionStringExcel:value"] + filePath;
                                ML.Result resultUsuarios = BL.Usuario.ConvertXSLXtoDataTable(connectionString);

                                if (resultUsuarios.Correct)
                                {
                                    ML.Result resultValidacion = BL.Usuario.ValidarExcel(resultUsuarios.Objects);
                                    HttpContext.Session.SetString("Display", "block");
                                    HttpContext.Session.SetString("File", fileName);
                                    if (resultValidacion.Objects.Count == 0)
                                    {
                                        resultValidacion.Correct = true;
                                        
                                        HttpContext.Session.SetString("PathArchivo", filePath);
                                        HttpContext.Session.SetString("Correct", "true");
                                    }
                                    else
                                    {
                                        resultValidacion.Correct = false;
                                        HttpContext.Session.SetString("Correct", "false");
                                        HttpContext.Session.SetString("PathArchivo", "error");                                       
                                    }                                  
                                                                 
                                    ViewBag.File = fileName;
                                    
                                    //return RedirectToAction("Index", resultValidacion);                                    
                                    return View("Index", resultValidacion);                                    
                                }
                                else
                                {
                                    ViewBag.Message = "El excel no contiene registros";
                                }
                            }
                        }
                        else
                        {
                            ViewBag.Message = "Favor de seleccionar un archivo .xlsx,.xls o .cvs. Verifique su archivo";
                        }
                    }
                    else
                    {
                        ViewBag.Message = "No selecciono ningun archivo, Seleccione uno correctamente";
                    }
                }
                else
                {
                    ViewBag.Message = "No seleccionó ningún archivo, intente de nuevo.";
                }
                
            }
            else
            {
                string rutaArchivoExcel = HttpContext.Session.GetString("PathArchivo");
                string connectionString = _configuration["ConnectionStringExcel:value"] + rutaArchivoExcel;

                ML.Result resultData = BL.Usuario.ConvertXSLXtoDataTable(connectionString);
                if (resultData.Correct)
                {
                    ML.Result resultErrores = new ML.Result();
                    resultErrores.Objects = new List<object>();

                    foreach (ML.Usuario usuarioItem in resultData.Objects)
                    {

                        ML.Result resultAdd = BL.Usuario.Add(usuarioItem);
                        if (!resultAdd.Correct)
                        {
                            resultErrores.Objects.Add("No se insertó el Usuario con UserName: " + usuarioItem.UserName + 
                                ", Nombre:" + usuarioItem.Nombre + ", Apellido Paterno:" + usuarioItem.ApellidoPaterno + 
                                ", Apellido Materno. " + usuarioItem.ApellidoMaterno + "Error: " + resultAdd.ErrorMessage);
                        }
                    }
                    if (resultErrores.Objects.Count > 0)
                    {

                        string fileError = Path.Combine(_environment.WebRootPath, @"~\Files\logErrores.txt");
                        using (StreamWriter writer = new StreamWriter(fileError))
                        {
                            foreach (string ln in resultErrores.Objects)
                            {
                                writer.WriteLine(ln);
                            }
                        }
                        ViewBag.Message = "Los usuarios no han sido registrados correctamente, verifique el contenido del archivo.";
                    }
                    else
                    {
                        HttpContext.Session.SetString("Display", "none");
                        HttpContext.Session.SetString("File", "");
                        HttpContext.Session.SetString("Correct", "");
                        HttpContext.Session.Remove("PathArchivo");
                        ViewBag.Message = "Los usuarios han sido registrados correctamente";
                    }

                }

            }
            return PartialView("Modal");
        }

    }//Controller
}//NS

PL/Views/CargaMasivaUsuario/Index.cshtml
@model ML.Result
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <h2>Seleccione con que tipo de archivo desea hacer la carga</h2>
    </div>
    <hr />
    
    <div class="row justify-content-around">
        <div class="col">
            <button class="btn btn-success w-100" id="btnExcel" name="btnExcel" onclick="show('uploadExcel')"><h2>Excel</h2></button>

            @using (Html.BeginForm("Excel", "CargaMasivaUsuario", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
            <div style="display:@ViewBag.Display;" id="uploadExcel">
                <input class="form-control" type="file" name="archivoExcel" id="archivoExcel" />
                <div style="text-align:center">
                    <br />                    
                
                    @if (Model.Correct || ViewBag.Correct == true)
                    {                        
                        <p>Archivo a subir: @ViewBag.File</p>
                        <input type="submit" value="Subir" class="btn btn-outline-success" />
                    }
                    else
                    {
                        <input type="submit" value="Procesar" class="btn btn-success" />
                    }
                </div>
            </div>
            }
        </div>
        <div class="col">
            <button class="btn btn-info w-100" id="btnTxt" name="btnTxt" onclick="show('uploadTxt')"><h2>Txt</h2></button>
            @using (Html.BeginForm("Index","CargaMasivaUsuario",FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div style="display:none" id="uploadTxt">
                    <input class="form-control" type="file" name="archivoTxt" id="archivoTxt" />
                    <div style="text-align:center">
                        <br />
                        <input type="submit" value="Procesar" class="btn btn-info" />
                    </div>                    
                </div>
            }  
            
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-12">
            @if (Model.Objects != null)
            {
                @if (Model.Objects.Count > 0)
                {
                    <br />
                    <p>Nombre del archivo: @ViewBag.File</p>
                    <hr />
                    <table class="table table-dark table-bordered table-responsive">
                        <thead>
                            <tr class="text-center">
                                <td>IdRegistro</td>
                                <td>Error</td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (ML.ErrorExcel error in Model.Objects)
                            {
                                <tr class="text-center">
                                    <td>@error.IdRegistro</td>
                                    <td>@error.Mensaje</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
            }
            else
            {

            }
        </div>
    </div>
    
</div>

@section Scripts {
        <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
        <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
        <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

    <script type="text/javascript">

        //function validateFileTxt() {
        //    var allowedExtension = ['txt'];
        //    var fileExtension = document.getElementById('archivoTxt').value.split('.').pop().toLowerCase();
        //    var isValidFile = false;
        //    for (var index in allowedExtension) {
        //        if (fileExtension === allowedExtension[index]) {
        //            isValidFile = true;
        //            break;
        //        }
        //    }
        //    if (!isValidFile) {
        //        alert('La extensión permitida es: *.' + allowedExtension.join(', *.'));
        //        document.getElementById('archivoTxt').value = ""
        //    }
        //    return isValidFile;
        //}

        //function validateFileExcel() {
        //    var allowedExtension = ['xlsx'];
        //    var fileExtension = document.getElementById('archivoExcel').value.split('.').pop().toLowerCase();
        //    var isValidFile = false;
        //    for (var index in allowedExtension) {
        //        if (fileExtension === allowedExtension[index]) {
        //            isValidFile = true;
        //            break;
        //        }
        //    }
        //    if (!isValidFile) {
        //        alert('La extensión permitida es: *.' + allowedExtension.join(', *.'));
        //        document.getElementById('archivoExcel').value = ""
        //    }
        //    return isValidFile;
        //}

        function show(idDiv){
            var div = document.getElementById(idDiv)
            if (div.style.display === "none") {
                div.style.display = "block";
            } else {
                div.style.display = "none";
            }
        }


    </script>       
}

PL/Views/CargaMasivaUsuario/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "Index", "CargaMasivaUsuario", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>