PL/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class ProductoController : Controller
    {
        //Inyeccion de dependencias-- patron de diseño
        private readonly IConfiguration _configuration;
        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _hostingEnvironment;

        public ProductoController(IConfiguration configuration, Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnvironment)
        {
            _configuration = configuration;
            _hostingEnvironment = hostingEnvironment;
        }
        // GET: Producto
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Producto producto = new ML.Producto();

                //Sin ServicioWeb
            /*ML.Result result = BL.Producto.GetAll(producto);

            if (result.Correct)
            {
                producto.Productos = result.Objects;
                return View(producto);
            }
            else
            {
                return View(producto);
            }*/

            ML.Result result = new ML.Result();
            result.Objects = new List<object>();

                //Con ServicioWeb
            try
            {

                using (var client = new HttpClient())
                {
                    string urlApi = _configuration["urlApi"];
                    client.BaseAddress = new Uri(urlApi);

                    var responseTask = client.GetAsync("Producto/GetAll");
                    responseTask.Wait();

                    var resultServicio = responseTask.Result;

                    if (resultServicio.IsSuccessStatusCode)
                    {
                        var readTask = resultServicio.Content.ReadAsAsync<ML.Result>();
                        readTask.Wait();

                        foreach (var resultItem in readTask.Result.Objects)
                        {
                            ML.Producto resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Producto>(resultItem.ToString());
                            result.Objects.Add(resultItemList);
                        }
                    }
                    producto.Productos = result.Objects;
                }

            }
            catch (Exception ex)
            {
                ViewBag.Message = "Error al mostrar los datos. " + ex.Message;
                return PartialView("Modal");
            }

            return View(producto);
        }//GetAll

        [HttpGet]
        public ActionResult Form(int? idProducto)
        {
            ML.Result resultProveedor = BL.Proveedor.GetAll();
            ML.Result resultDepartamento = BL.Departamento.GetAll();
            ML.Result resultArea = BL.Area.GetAll();

            ML.Producto producto = new ML.Producto();

            producto.Departamento = new ML.Departamento();
            producto.Proveedor = new ML.Proveedor();
            producto.Departamento.Area = new ML.Area();

            if (resultProveedor.Correct && resultDepartamento.Correct)
            {
                producto.Departamento.Departamentos = resultDepartamento.Objects;
                producto.Proveedor.Proveedores = resultProveedor.Objects;
                producto.Departamento.Area.Areas = resultArea.Objects;
            }//if

            if (idProducto == null)
            {
                //Add Form Vacio
                return View(producto);

            }//if
            else
            {
                //GetById Sin ServiciosWeb
                //ML.Result result = BL.Producto.GetById(idProducto.Value);

                //GetById Con ServicioWeb
                ML.Result result = new ML.Result();
                result.Object = new object();
                using (var client = new HttpClient())
                {
                    string urlApi = _configuration["urlApi"];
                    client.BaseAddress = new Uri(urlApi);

                    var responseTask = client.GetAsync("Producto/GetById?idProducto=" + idProducto);
                    responseTask.Wait();

                    var resultServicio = responseTask.Result;

                    if (resultServicio.IsSuccessStatusCode)
                    {
                        var readTask = resultServicio.Content.ReadAsAsync<ML.Result>();
                        readTask.Wait();
                        var resultItem = readTask.Result.Object;

                        ML.Producto resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Producto>(resultItem.ToString());
                        result.Object = resultItemList;

                        result.Correct = true;
                    }
                }

                if (result.Correct)
                {
                    producto = (ML.Producto)result.Object;

                    resultProveedor = BL.Proveedor.GetAll();
                    resultDepartamento = BL.Departamento.GetByIdArea(producto.Departamento.Area.IdArea);

                    producto.Proveedor.Proveedores = resultProveedor.Objects;
                    producto.Departamento.Departamentos = resultDepartamento.Objects;
                    producto.Departamento.Area.Areas = resultArea.Objects;

                    //Update
                    return View(producto);
                }//if
                else
                {
                    ViewBag.Message = "Error al mostrar la información del producto";
                    return View("Modal");
                }//else
            }//else
        }//Form

        [HttpPost]
        public ActionResult Form(ML.Producto producto)
        {
            //Sin ServicioWeb
            /*ML.Result result = new ML.Result();
            IFormFile file = Request.Form.Files["fuImage"];

            if (file != null)
            {
                byte[] imagen = ImagenABase64(file);
                producto.Imagen = Convert.ToBase64String(imagen);
            }

            if (producto.IdProducto == 0)
            {
                //Add
                result = BL.Producto.Add(producto);

                if (result.Correct)
                {
                    ViewBag.Message = "¡Producto registrado correctamente!";
                }
                else
                {
                    ViewBag.Message = "Error al registrar el producto...";
                }
                return View("Modal");
            }//if
            else
            {
                //Update
                result = BL.Producto.Update(producto);
                if (result.Correct)
                {
                    ViewBag.Message = "¡Se actualizó el registro correctamente!";
                }//if
                else
                {
                    ViewBag.Message = "Error al actualizar el registo...";
                }//else
                return View("Modal");
            }*/

            //Con ServicioWeb
            IFormFile file = Request.Form.Files["fuImage"];

            if (file != null)
            {
                byte[] imagen = ImagenABase64(file);

                producto.Imagen = Convert.ToBase64String(imagen);
            }
            //Add
            if (producto.IdProducto == 0)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_configuration["urlApi"]);

                    //HTTP POST
                    var postTask = client.PostAsJsonAsync("Producto/Add", producto);
                    postTask.Wait();

                    var result = postTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        ViewBag.Message = "Se ha ingresado el registro.";
                    }
                    else
                    {
                        ViewBag.Message = "No se ha ingresado el registro.";
                    }
                    return PartialView("Modal");
                }//using
            }//if

            //Update
            else
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_configuration["urlApi"]);

                    //HTTP POST
                    var postTask = client.PostAsJsonAsync("Producto/Update", producto);
                    postTask.Wait();

                    var result = postTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        ViewBag.Message = "Se ha actualizado el producto.";
                        return PartialView("Modal");
                    }
                    else
                    {
                        ViewBag.Message = "No se ha actualizado el producto.";
                        return PartialView("Modal");
                    }
                }
            }
        }//Form

        [HttpGet]
        public ActionResult Delete(int idProducto)
        {
            //Sin ServicioWeb
            /*ML.Result result = BL.Producto.Delete(idProducto);
            if (result.Correct)
            {
                ViewBag.Message = "Registro eliminado correctamente!";
            }
            else
            {
                ViewBag.Message = "Error al eliminar el registro...";
            }
            return View("Modal");*/

            //Con ServicioWeb
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_configuration["urlApi"]);

                //HTTP POST
                var deleteTask = client.PostAsync("Producto/Delete?idProducto=" + idProducto, null);
                deleteTask.Wait();

                var result = deleteTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    ViewBag.Message = "Se ha eliminado el producto.";
                    return PartialView("Modal");
                }
                else
                {

PL/Views/Producto/Form.cshtml
@model ML.Producto

@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2><i class="fa-solid fa-cart-shopping fa-bounce" style="color:royalblue"></i> Producto</h2>
            <p>Ingrese los datos del producto a registrar</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Producto", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">
                    <div class="row">
                        <div>
                            @Html.LabelFor(model => model.IdProducto, new { @class = "visually-hidden" })
                            @Html.TextBoxFor(model => model.IdProducto, new { @class = "visually-hidden" })
                            @Html.ValidationMessageFor(model => model.IdProducto)
                            @*hidden*@
                        </div>

                    </div><!-- row -->

                    <br />

                    <div class="row">
                        
                        <div class="col">
                            @Html.LabelFor(model => model.Nombre)
                            <div class="input-group">
                                <span class="input-group-text"><i class="fa-solid fa-quote-right"></i></span>
                                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })
                                @Html.ValidationMessageFor(model => model.Nombre)
                            </div>
                        </div>

                        <div class="col">
                            @Html.LabelFor(model => model.PrecioUnitario)
                            <div class="input-group">
                                <span class="input-group-text"><i class="fa-solid fa-dollar-sign"></i></span>
                                @Html.TextBoxFor(model => model.PrecioUnitario, new { @class = "form-control", @id = "txtPrecioUnitario" })
                                @Html.ValidationMessageFor(model => model.PrecioUnitario)
                            </div>
                        </div>

                        <div class="col">
                            @Html.LabelFor(model => model.Stock)
                            <div class="input-group">
                                <span class="input-group-text"><i class="fa-solid fa-box-open"></i></span>
                                @Html.TextBoxFor(model => model.Stock, new { @class = "form-control", @id = "txtStock" })
                                @Html.ValidationMessageFor(model => model.Stock)
                            </div>
                        </div>
                                                
                    </div><!-- row -->

                    <br />

                    <div class="row">                        

                        <div class="col">
                            @Html.LabelFor(model => model.Departamento.Area)
                            <div class="input-group">
                                <span class="input-group-text"><i class="fa-solid fa-shop"></i></span>
                                @Html.DropDownListFor(model => model.Departamento.Area.IdArea,
                            new SelectList(Model.Departamento.Area.Areas, "IdArea", "Nombre"),
                            "Selecciona un Area", new { @class = "form-control", @id = "ddlArea" })
                            </div>
                        </div>                        

                        <div class="col">
                            @Html.LabelFor(model => model.Departamento)
                            <div class="input-group">
                                <span class="input-group-text"><i class="fa-solid fa-basket-shopping"></i></span>
                                @Html.DropDownListFor(model => model.Departamento.IdDepartamento,
                            new SelectList(Model.Departamento.Departamentos, "IdDepartamento", "Nombre"),
                            "Selecciona un Departamento", new { @class = "form-control" , @id = "ddlDepartamento"})
                            </div>
                        </div>

                        <div class="col">
                            @Html.LabelFor(model => model.Proveedor)
                            <div class="input-group">
                                <span class="input-group-text"><i class="fa-solid fa-truck"></i></span>
                                @Html.DropDownListFor(model => model.Proveedor.IdProveedor,
                            new SelectList(Model.Proveedor.Proveedores, "IdProveedor", "Nombre"),
                            "Selecciona un Proveedor", new { @class = "form-control" })
                            </div>
                        </div>

                    </div><!-- row -->

                    <br />

                    <div class="row">                        

                        <div class="col-8">
                            @Html.LabelFor(model => model.Descripcion)
                            <div class="input-group">
                                <span class="input-group-text"><i class="fa-solid fa-align-justify"></i></span>
                                @Html.TextBoxFor(model => model.Descripcion, new { @class = "form-control", @id = "txtDescripcion" })
                                @Html.ValidationMessageFor(model => model.Descripcion)
                            </div>
                        </div>                                              

                    </div><!-- row -->

                    <br />

                    <div class="row">
                        
                        <div class="col-5">
                            <div class="input-group-text mb-5">
                                <span class="input-group-text" id="basic-text1"><i class="fa-solid fa-image"></i></span>
                                <input id="fuImage" type='file' class="form-control" name="fuImage" onchange="validateFile(this), readURL(this);  " />
                            </div>                            

                            @if (Model.Imagen != null)
                            {

                                <img id="Img" src="data:image/*;base64,@Model.Imagen" style="width:150px ; height:150px" />

                            }
                            else
                            {
                                <img id="Img" src="~/Imagenes/ProductoDefault.jpg" style="width:150px ; height:150px" />
                            }
                        </div>
                        @Html.HiddenFor(model => model.Imagen)
                    </div>

                    <br />

                    <div class="row">
                        <hr />
                        <div class="col-md-3">                            
                            <input type="submit" value="Guardar" class="btn btn-success" />
                            @Html.ActionLink("Regresar", "GetAll", "Producto", htmlAttributes: new { @class = "btn btn-danger" })
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div><!--Container-->

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#ddlArea").change(function () {
                $("#ddlDepartamento").empty();
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("DepartamentoGetByIdArea")',
                    datatype: 'json',
                    data: { idArea: $("#ddlArea").val() },
                    success: function (departamentos) {
                        $("#ddlDepartamento").append('<option value="0">' + 'Selecciona un Departamento' + '</option>');
                        $.each(departamentos, function (i, departamentos) {
                            $("#ddlDepartamento").append('<option value="'
                                + departamentos.idDepartamento + '">'
                                + departamentos.nombre + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed: ' + ex);
                    }
                });//ajax
            });//changeFunction
        });//documentReady

        function validateFile() {
            var allowedExtension = ['jpeg', 'jpg', 'png'];
            var fileExtension = document.getElementById('fuImage').value.split('.').pop().toLowerCase();
            var isValidFile = false;
            for (var index in allowedExtension) {
                if (fileExtension === allowedExtension[index]) {
                    isValidFile = true;
                    break;
                }
            }
            if (!isValidFile) {
                alert('Las extensiones permitidas son : *.' + allowedExtension.join(', *.'));
                document.getElementById('fuImage').value = ""
            }
            return isValidFile;
        }//validateFile

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#Img').attr('src', e.target.result);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }//readURL
    </script>
}

PL/Views/Producto/GetAll.cshtml
@model ML.Producto
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col">
            <h2><i class="fa-solid fa-cart-shopping fa-bounce" style="color:royalblue"></i> Productos</h2>
        </div>        
        <div class="col" style="text-align:right">
            @Html.ActionLink("Agregar Producto", "Form", "Producto", htmlAttributes: new { @class = "btn btn-success" })
            
        </div><!--style-->
        <p>Presione el boton de "Agregar" si desea registrar un nuevo producto</p>  
        <hr />
    </div> <!--row-->

    <div class="row" style="text-align:center">

        <div class="col-1 col-md-12">

            @if (Model.Productos != null)
            {

                <table class="table table-bordered table-responsive" id="tbProducto">
                    <thead>
                        <tr>
                            <td class="text-center col-xs-1" style="font-weight:bold;">Editar</td>
                            <td class="text-center col-xs-1" style="font-weight:bold;">Eliminar</td>

                            <td class="visually-hidden">IdProducto</td>
                            <td class="text-center" style="font-weight:bold;">Nombre</td>
                            <td class="text-center" style="font-weight:bold;">Precio unitario</td>
                            <td class="text-center" style="font-weight:bold;">Stock</td>
                            <td class="visually-hidden">IdProveedor</td>
                            <td class="text-center" style="font-weight:bold;">Proveedor</td>
                            <td class="visually-hidden">IdDepartamento</td>
                            <td class="text-center" style="font-weight:bold;">Departamento</td>
                            <td class="text-center" style="font-weight:bold;">Descripcion</td>
                            <td class="text-center" style="font-weight:bold;">Imagen</td>

                        </tr>
                    </thead>

                    <tbody>
                        @foreach (ML.Producto producto in Model.Productos)
                        {
                            <tr>
                                <td class="text-center">
                                    <a class="btn btn-warning"
                               href="@Url.Action("Form", "Producto",
                                                            new { IdProducto = producto.IdProducto})"><i class="fa-regular fa-pen-to-square"></i></a>

                                </td>
                                <td class="text-center">
                                    <a class="btn btn-danger"
                               href="@Url.Action("Delete","Producto",
                                                            new { IdProducto = producto.IdProducto })"><i class="fa-solid fa-trash"></i></a>
                                </td>

                                <td class="visually-hidden">@producto.IdProducto</td>
                                <td class="col-sm-2">@producto.Nombre</td>
                                <td class="col-xs-1">@producto.PrecioUnitario</td>
                                <td class="col-xs-1">@producto.Stock</td>
                                <td class="visually-hidden">@producto.Proveedor.IdProveedor</td>
                                <td class="col-sm-1">@producto.Proveedor.Nombre</td>
                                <td class="visually-hidden">@producto.Departamento.IdDepartamento</td>
                                <td class="col-sm-1">@producto.Departamento.Nombre</td>
                                <td class="col-sm-2">@producto.Descripcion</td>
                                <td>
                                    @if (producto.Imagen != null && producto.Imagen != "")
                                    {

                                        <img id="Img" src="data:image/*;base64,@producto.Imagen" style="width:150px ; height:150px" />

                                    }
                                    
                                    @if (producto.Imagen.Equals("") || producto.Imagen == null)
                                    {
                                        <img id="Img" src="~/Imagenes/ProductoDefault.jpg" style="width:150px ; height:150px" />
                                    }

                                </td>

                            </tr>
                        }
                    </tbody>
                </table>
            }

            else
            {
                <div class="alert alert-danger" role="alert">Ocurrio un error!!</div>
            }

        </div>

    </div>

</div><!--container-->

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#tbProducto').DataTable({
                searching: false,
                "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "Todos"]],
                autoWidth: false,
                columnDefs: [
                    {
                        targets: ['_all'],
                        className: 'mdc-data-table__cell',
                    },
                ],
                language: {
                    url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
                },
            });
        });
    </script>
}

PL/Views/Producto/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "Producto", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>