PL/Controllers/DepartamentoController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class DepartamentoController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Result result = BL.Departamento.GetAll();
            ML.Departamento departamento = new ML.Departamento();
            if (result.Correct)
            {
                departamento.Departamentos = result.Objects;
                return View(departamento);
            }
            else
            {
                return View(departamento);
            }
        }//GetAll

        [HttpGet]
        public ActionResult Form(int? idDepartamento)
        {
            ML.Result resultArea = BL.Area.GetAll();
            ML.Departamento departamento = new ML.Departamento();
            departamento.Area = new ML.Area();

            if (resultArea.Correct)
            {
                departamento.Area.Areas = resultArea.Objects;
            }//if

            if (idDepartamento == null)
            {
                //Add FormVacio
                return View(departamento);
            }//if
            else
            {
                //GetById
                ML.Result result = BL.Departamento.GetById(idDepartamento.Value);

                if (result.Correct)
                {
                    departamento = (ML.Departamento)result.Object;
                    departamento.Area.Areas = resultArea.Objects;

                    //Update
                    return View(departamento);
                }//if
                else
                {
                    ViewBag.Message = "Error al mostrar la información.";
                    return View("Modal");
                }//else                
            }//else
        }//Form

        [HttpPost]
        public ActionResult Form(ML.Departamento departamento)
        {
            ML.Result result = new ML.Result();
            if (departamento.IdDepartamento == 0)
            {
                //Add
                result = BL.Departamento.Add(departamento);
                if (result.Correct)
                {
                    ViewBag.Message = "¡Se registró correctamente!";
                }
                else
                {
                    ViewBag.Message = "Error!";
                }
                return View("Modal");
            }
            else
            {
                //Update
                result = BL.Departamento.Update(departamento);
                if (result.Correct)
                {
                    ViewBag.Message = "¡Se actualizó correctamente el registro!";
                }
                else
                {
                    ViewBag.Message = "Error al actualizar el registro...";
                }
                return View("Modal");
            }
        }//Form

        [HttpGet]
        public ActionResult Delete(int idDepartamento)
        {
            ML.Result result = BL.Departamento.Delete(idDepartamento);
            if (result.Correct)
            {
                ViewBag.Message = "Registro eliminado correctamente";
            }
            else
            {
                ViewBag.Message = "Error al eliminar el registro.";
            }
            return View("Modal");
        }
    }//ClassController
}//NS

PL/Controllers/VentaController.cs
using DL;
using Microsoft.AspNetCore.Mvc;
using ML;

namespace PL.Controllers
{
    public class VentaController : Controller
    {
        // GET: Producto
        [HttpGet]
        public ActionResult ProductoGetAll()
        {
            ML.Producto producto = new ML.Producto();
            producto.Departamento = new ML.Departamento();
            producto.Departamento.Area = new ML.Area();

            ML.Result resultArea = BL.Area.GetAll();
            ML.Result result = BL.Producto.GetAll(producto);
            ML.Result resultDepartamento = BL.Departamento.GetByIdArea(producto.Departamento.Area.IdArea);
            
            producto.Productos = result.Objects;
            producto.Departamento.Departamentos = resultDepartamento.Objects;
            producto.Departamento.Area.Areas = resultArea.Objects;
                
            return View(producto);            
        }//GetAll

        [HttpPost]
        public ActionResult ProductoGetAll(ML.Producto producto)
        {
            producto.IdDepartamento = producto.Departamento.IdDepartamento;
            ML.Result result = BL.Producto.GetAll(producto);

                ML.Result resultArea = BL.Area.GetAll();                
                producto.Departamento.Area.Areas = resultArea.Objects;
                ML.Result resultDepartamento = BL.Departamento.GetByIdArea(producto.Departamento.Area.IdArea);
                producto.Departamento.Departamentos = resultDepartamento.Objects;

                producto.Productos = result.Objects;
                return View(producto);            
        }//GetAll

        [HttpGet]
        public ActionResult Carrito(int? idProducto)
        {
            ML.Producto producto = new ML.Producto();
            //GetById
            ML.Result result = BL.Producto.GetById(idProducto.Value);

            if (result.Correct)
            {
                producto.Proveedor = new ML.Proveedor();
                producto.Departamento = new ML.Departamento();
                producto.Departamento.Area = new ML.Area();                
                producto = (ML.Producto)result.Object;               

                ML.Result resultProveedor = BL.Proveedor.GetAll();
                ML.Result resultArea = BL.Area.GetAll();
                ML.Result resultDepartamento = BL.Departamento.GetByIdArea(producto.Departamento.Area.IdArea);

                producto.Proveedor.Proveedores = resultProveedor.Objects;
                producto.Departamento.Departamentos = resultDepartamento.Objects;
                producto.Departamento.Area.Areas = resultArea.Objects;

                producto.Productos = result.Objects;

                //Update
                return View(producto);
            }//if
            else
            {
                ViewBag.Message = "Error al mostrar la información del producto";
                return View("Modal");
            }//else
        }//Carrito

        [HttpGet]
        public ActionResult ProductoDelete(int idProducto)
        {
            ML.Result result = BL.Producto.Delete(idProducto);
            if (result.Correct)
            {
                ViewBag.Message = "Registro eliminado correctamente!";
            }
            else
            {
                ViewBag.Message = "Error al eliminar el registro...";
            }
            return View("Modal");
        }//Delete

        public ActionResult SumarCantidad(int idProducto)
        {
            ML.VentaProducto venta = new ML.VentaProducto();
            venta.VentaProductos = new List<object>();
            
            GetCarrito(venta);

            foreach (ML.Producto item in venta.VentaProductos)
            {
                if (item.IdProducto == idProducto)
                {
                    item.Cantidad += 1;
                }
            }
            HttpContext.Session.SetString("Producto", Newtonsoft.Json.JsonConvert.SerializeObject(venta.VentaProductos));
            return View("ResumenCompra", venta);
        }

        public ActionResult RestarCantidad(int idProducto)
        {
            ML.VentaProducto venta = new ML.VentaProducto();
            venta.VentaProductos = new List<object>();

            GetCarrito(venta);

            foreach (ML.Producto item in venta.VentaProductos)
            {
                if (item.IdProducto == idProducto)
                {
                    item.Cantidad -= 1;
                }
            }
            HttpContext.Session.SetString("Producto", Newtonsoft.Json.JsonConvert.SerializeObject(venta.VentaProductos));
            return View("ResumenCompra", venta);
        }

        public ActionResult Eliminar(int idProducto)
        {
            ML.VentaProducto venta = new ML.VentaProducto();
            venta.VentaProductos = new List<object>();

            GetCarrito(venta);

            var indice = 0; //variable para el index

            foreach (ML.Producto item in venta.VentaProductos)
            {// foreach que recorre el objeto venta producto
                if (item.IdProducto == idProducto)
                {// if que compara el id de el producto con el de ventaproducto

                    indice = venta.VentaProductos.IndexOf(item);//index 

                }
            }

            venta.VentaProductos.RemoveAt(indice);
            HttpContext.Session.SetString("Producto", Newtonsoft.Json.JsonConvert.SerializeObject(venta.VentaProductos));

            return View("ResumenCompra", venta);
        }

        public JsonResult ProductoAdd(int idProducto)
        {
            ML.Result result = BL.Producto.GetById(idProducto);

            return Json(result.Object);
        }

        public JsonResult DepartamentoGetByIdArea(int idArea)
        {
            ML.Result result = BL.Departamento.GetByIdArea(idArea);

            return Json(result.Objects);
        }//JsonResult

        public byte[] ImagenABase64(IFormFile foto)
        {
            using var fileStream = foto.OpenReadStream();

            byte[] bytes = new byte[fileStream.Length];
            fileStream.Read(bytes, 0, (int)fileStream.Length);

            return bytes;
        }//imagenABase64

        [HttpGet]
        public ActionResult CartPost(int idProducto)
        {
            ML.Result result = BL.Producto.GetById(idProducto);
            ML.Producto producto = (ML.Producto)result.Object;
            bool existe = false;
            ML.VentaProducto ventaProducto = new ML.VentaProducto();
            ventaProducto.VentaProductos = new List<object>();

            if (HttpContext.Session.GetString("Producto") == null)
            {
                producto.Cantidad = producto.Cantidad = 1;
                producto.Subtotal = producto.PrecioUnitario * producto.Cantidad;
                ventaProducto.VentaProductos.Add(producto);
                HttpContext.Session.SetString("Producto", Newtonsoft.Json.JsonConvert.SerializeObject(ventaProducto.VentaProductos));
                var session = HttpContext.Session.GetString("Producto");
            }
            else
            {
                GetCarrito(ventaProducto);
                foreach (ML.Producto venta in ventaProducto.VentaProductos.ToList())
                {
                    if (producto.IdProducto == venta.IdProducto)
                    {
                        venta.Cantidad = venta.Cantidad + 1;   //True
                        venta.Subtotal = venta.PrecioUnitario * venta.Cantidad;
                        existe = true;
                    }
                    else
                    {
                        existe = false;
                    }
                    if (existe == true)
                    {
                        break;
                    }
                }
                if (existe == false)
                {
                    producto.Cantidad = producto.Cantidad = 1;
                    producto.Subtotal = producto.Cantidad * producto.PrecioUnitario;
                    ventaProducto.VentaProductos.Add(producto);
                }
                HttpContext.Session.SetString("Producto", Newtonsoft.Json.JsonConvert.SerializeObject(ventaProducto.VentaProductos));
            }
            if (HttpContext.Session.GetString("Producto") != null)
            {
                ViewBag.Message = "Se ha agregado el producto a tu carrito!";
                return PartialView("Modal");
            }
            else
            {
                ViewBag.Message = "No se pudo agregar tu producto ):";
                return PartialView("Modal");
            }

        }

        [HttpGet]
        public ActionResult ResumenCompra(ML.VentaProducto ventaProducto)
        {
            decimal costoTotal = 0;
            if (HttpContext.Session.GetString("Producto") == null)
            {
                return View();
            }
            else
            {
                ventaProducto.VentaProductos = new List<object>();
                GetCarrito(ventaProducto);
                ventaProducto.Total = costoTotal;
            }

            return View(ventaProducto);
        }
        public ML.VentaProducto GetCarrito(ML.VentaProducto ventaProducto)
        {
            var ventaSession = Newtonsoft.Json.JsonConvert.DeserializeObject<List<object>>(HttpContext.Session.GetString("Producto"));

            foreach (var obj in ventaSession)
            {
                ML.Producto objProducto = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Producto>(obj.ToString());
                ventaProducto.VentaProductos.Add(objProducto);
            }
            return ventaProducto;
        }
    }//Controller
}//NS

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PL.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="GetAll">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departamento" asp-action="GetAll">Departamentos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="GetAll">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venta" asp-action="ProductoGetAll">Venta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CargaMasivaUsuario" asp-action="Index">Carga Masiva(Usuario)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venta" asp-action="ResumenCompra">Carrito</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>